// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package sophosutm

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "sophosutm", asset.ModuleFieldsPri, AssetSophosutm); err != nil {
		panic(err)
	}
}

// AssetSophosutm returns asset data.
// This is the base64 encoded gzipped contents of module/sophosutm.
func AssetSophosutm() string {
	return "eJykk0FyszAMhfecQpN9/gOw+G+QVdt1xrFl0MTYjiUnTU/fgaYpdDxNi7VgIaHvvQf2Fo54bYFD7ANnGRoAIXHYwube2zQABlknikLBt/C/AYCvHdgFkx02AJbQGW6n8Ra8GnCJHkuuEVvoUsjx1imwx/qggg0JokpMvoOniQUudPzv9t5cci5rKeFFOXcflJTHSuhQMbZwQFGzvkGrspP9JNCCVY5xMS6a/tn4y/NuYb4UYB5Cmb0JgyK/mH4mOeL1EpK5z8qIKFFowCKBvGCH6QEhS1+hn6Wv1D+zVr6OoZXu0axPoZXUGTB4Jl3e/5UB47nOAL5qnE4rrzdhyQkmpUdMBSU7l/BUF+f7Lf6jB6o4C+Nz/XZMwZKrACS0mGafZwXglJFlPYDpreLPcT6sl878IPl7AAAA//8n5qMO"
}
